name: Laravel Sail Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Copy .env and update DB settings
      run: |
        cp .env.example .env
        sed -i 's/DB_HOST=.*/DB_HOST=mysql/g' .env
        sed -i 's/REDIS_HOST=.*/REDIS_HOST=redis/g' .env
        cat .env | grep DB_HOST
        cat .env | grep REDIS_HOST

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Composer dependencies
      run: docker run --rm -v "$(pwd):/app" composer:latest composer install --no-progress --no-interaction

    - name: Start Laravel Sail
      run: ./vendor/bin/sail up -d

    - name: Check running containers
      run: docker ps -a

    - name: Wait for services to be ready
      run: sleep 10

    - name: Check Redis connection
      run: ./vendor/bin/sail exec redis redis-cli ping

    - name: Generate application key
      run: ./vendor/bin/sail artisan key:generate

    - name: Run database migrations
      run: ./vendor/bin/sail artisan migrate --force

    - name: Run tests
      run: ./vendor/bin/sail test --coverage

    - name: Stop Laravel Sail
      if: always()
      run: ./vendor/bin/sail down
